all: HW07

HW07:
	g++ -std=c++11 -c fatih_oguz_151044025.cpp
	g++ -std=c++11 -c read2.cpp
	g++ -std=c++11 -c employee.cpp
	g++ -std=c++11 -c AcademicPersonnel.cpp
	g++ -std=c++11 -c AdministrativePersonnel.cpp
	g++ -std=c++11 -c Lecturer.cpp
	g++ -std=c++11 -c University.cpp
	g++ -std=c++11 -c ResearchAsistant.cpp
	g++ -std=c++11 -c Secretary.cpp
	g++ -std=c++11 -c Officer.cpp
	g++ -std=c++11 -c read.cpp
	g++ -std=c++11 -c EducationSystem.cpp
	g++ -std=c++11 -c CommunistEducation.cpp
	g++ -std=c++11 -c LiberalEducation.cpp
	g++ -std=c++11 -c CapitalistEducation.cpp
	g++ -std=c++11 -c story.cpp
	g++ -o HW07 fatih_oguz_151044025.o read2.o employee.o AcademicPersonnel.o AdministrativePersonnel.o Lecturer.o University.o ResearchAsistant.o Secretary.o Officer.o read.o EducationSystem.o CommunistEducation.o LiberalEducation.o CapitalistEducation.o story.o
	./HW07
clean:
	rm *.o HW07
