all: HW05

HW05:
	g++ -std=c++0x -c fatih_oguz_151044025.cpp
	g++ -std=c++0x -c employee.cpp
	g++ -std=c++0x -c AcademicPersonnel.cpp
	g++ -std=c++0x -c AdministrativePersonnel.cpp
	g++ -std=c++0x -c Lecturer.cpp
	g++ -std=c++0x -c University.cpp
	g++ -std=c++0x -c ResearchAsistant.cpp
	g++ -std=c++0x -c Secretary.cpp
	g++ -std=c++0x -c Officer.cpp
	g++ -std=c++0x -c read.cpp

	g++ -o HW05 fatih_oguz_151044025.o employee.o AcademicPersonnel.o AdministrativePersonnel.o Lecturer.o University.o ResearchAsistant.o Secretary.o Officer.o read.o
	./HW05
clean:
	rm *.o HW05
